### ISSUE TITLE
Multiverse Nether / The End maps don't work?

### ISSUE THREAD

**Issue by VL4DST3R** [BlueMap-Minecraft/BlueMap#112]
**BlueMap Version:**
*`BlueMap-1.2.0-snap-spigot-1.16.1`*

I am (not) using:
- mods 
- resourcepacks

**Description:**
This may be a duplicate of #103 but figured i should ask anyway.
When pointing to a nether/end dimension following the example formatting (`worlds/hub_nether/DIM-1`) it complains there is no world to be found in that folder and barfs an error.

example console output:
```
10:40:20 [INFO] [BlueMap] Loading resources...
10:40:20 [INFO] [BlueMap] WebServer started.
10:40:20 [INFO] [BlueMap] Loading bluemap assets (1/3)...
10:40:20 [INFO] [BlueMap] Loading realms assets (2/3)...
10:40:20 [INFO] [BlueMap] Loading minecraft assets (3/3)...
10:40:20 [SEVERE] [BlueMap] Failed to load map 'hub_nether': Failed to get UUID for the world!
10:40:20 java.io.IOException: There is no world with this folder loaded: E:\My Games\For Games\Minecraft\Minecraft Bukkit Server\worlds\hub_nether\DIM-1
10:40:20 	at de.bluecolored.bluemap.bukkit.BukkitPlugin.getUUIDForWorldSync(BukkitPlugin.java:220) ~[?:?]
10:40:20 	at de.bluecolored.bluemap.bukkit.BukkitPlugin.lambda$getUUIDForWorld$1(BukkitPlugin.java:188) ~[?:?]
10:40:20 	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftFuture.run(CraftFuture.java:88) ~[Paper-1.16.1-b138.jar:git-Paper-138]
10:40:20 	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[Paper-1.16.1-b138.jar:git-Paper-138]
10:40:20 	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1298) ~[Paper-1.16.1-b138.jar:git-Paper-138]
10:40:20 	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[Paper-1.16.1-b138.jar:git-Paper-138]
10:40:20 	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[Paper-1.16.1-b138.jar:git-Paper-138]
10:40:20 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[Paper-1.16.1-b138.jar:git-Paper-138]
10:40:20 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[Paper-1.16.1-b138.jar:git-Paper-138]
10:40:20 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
10:40:20 [INFO] [BlueMap] Loaded!
```

If i instead point to the general `hub_nether` map folder (no DIM specified) it doesn't print any errors but doesn't load the map either.
Am i missing something? Also yes, i have the worlds under a `worlds` folder to keep them from spilling everywhere in the project root folder, but i doubt that's an issue since normal overworld maps load fine.

**Comment by TBlueF** [comment]
This is due to Multiverse not loading it's worlds on startup.. so BlueMap can't find them. But BlueMap needs the worlds UUID from the start to be able to work properly..

There is #109 which might fix this issue, but for now you need to make sure your multiverse worlds are loaded on startup.

I think you can do that with this multiverse config: https://github.com/Multiverse/Multiverse-Core/wiki/World-properties#auto-load, but i have not tested that ^^

**Comment by VL4DST3R** [comment]
Even so, BlueMap works fine with all the multiverse *overworld* maps i've thrown its way, it's just the nether/end that's having trouble with.

All the worlds i have available are set to auto-load, otherwise you won't be able to access them at all via the multiverse, so that config won't really help.

**Comment by VL4DST3R** [comment]
I would also like to know more info about how BlueMap world folder path works, since for overworld you don't need to point a dimension, while for nether/end you do? Is there something in the root of the world folder that's not available in the DIM-**X** folder (or maybe  the other way around?) which is causing this?

**Comment by TBlueF** [comment]
> Even so, BlueMap works fine with all the multiverse overworld maps

That is weird but unlikely caused by BlueMap... BlueMap is using Spigots `getServer().getWorlds()` to get the worlds, and matching them against their folder:
https://github.com/BlueMap-Minecraft/BlueMap/blob/master/implementations/spigot/src/main/java/de/bluecolored/bluemap/bukkit/BukkitPlugin.java#L215
If the world does not exist there, then your error occurs.

----

> I would also like to know more info about how BlueMap world folder path works, since for overworld you don't need to point a dimension, while for nether/end you do?

Spigot is doing some unusual stuff with its world-folders.
Usually a minecraft world has multiple dimensions ... the overworld in `world/`, the nether in `world/DIM-1` and the end in `world/DIM1`.
Spigot decided to split the dimensions in multiple worlds. To make the API easier i guess.. But it still needs to have the DIM-1 and the DIM1 folders if the world is a nether or an end dimension ...

BlueMap mainly needs the region files of a world. The region files are found in `world/region` for an overworld dimension and in `world/DIM-1/region` for the nether .. etc..
So it takes `<the worldfolder from your config>/region` to find them :)

Thats why you have to add those folders based on dimension :)

**Comment by VL4DST3R** [comment]
Gotcha, thanks for the explanation! Another thing to mention is the fact that Dynmap (another map rendering plugin) works just fine with multiverse servers, so i'm guessing a method exists to avoid whatever bs spigot is doing with that function. Do you **have** to get the worlds UUID that way? Or at all? Considering we're already pointing BlueMap to the right world folder from where to generate the render, wouldn't that be enough?

**Comment by VL4DST3R** [comment]
Finally, assuming this issue is indeed external (see what i mentioned above about Dynmap working just fine) should we forward this to Multiverse/Spigot devs? Another thing that may be worth to note is that i'm running the Paper fork of Spigot.

**Comment by TBlueF** [comment]
> should we forward this to Multiverse/Spigot devs

Wait with that.. I think at least #109 should be able to fix this..

----

> Do you have to get the worlds UUID that way?

Yes, the UUID's are for example needed to match the block-change events to the correct world to update the maps
Also live-player markers need the world UUIDs ^^

----

> i'm running the Paper fork of Spigot

I just tested multiverse on Spigot 1.16.1 and i did not manage to reproduce your issue, i created a mv-nether and bluemap could load it without any problems.. 
i have not used a world-container though, need to test that as well .. i'll also try it on paper

**Comment by VL4DST3R** [comment]
Okay, thanks for the help! Do tell me if you manage to reproduce it on your end. Also if i can help with anything else.

**Comment by TBlueF** [comment]
@VL4DST3R can you send me your Multiverse `config.yml` ? I am not able to reproduce, even when using paper and a world-container everything is working fine for me..

**Comment by VL4DST3R** [comment]
the multiverse core config?
```
#  -------------------------------------------------------------------------  #
# This is the MV2 Config. If you mess it up, copy the values out              #
# delete it, and it will be regenerated. Then use the ingame interface        #
# to add your values back via the "/mv conf" command.                         #
# When in-game, simply type: "/mv conf ?" for help.                           #
# A config with explanations can be found here:                               #
# https://github.com/Multiverse/Multiverse-Core/wiki/config.yml               #
#                                                                             #
#                                                                             #
#  IMPORTANT !! IMPORTANT !! IMPORTANT !! IMPORTANT !! IMPORTANT !!IMPORTANT  #
#                                                                             #
# Do NOT delete this line from your config!!!!                                #
# ==: com.onarandombox.MultiverseCore.MultiverseCoreConfiguration             #
#                                                                             #
#  IMPORTANT !! IMPORTANT !! IMPORTANT !! IMPORTANT !! IMPORTANT !!IMPORTANT  #
#  -------------------------------------------------------------------------  #

multiverse-configuration:
  ==: com.onarandombox.MultiverseCore.MultiverseCoreConfiguration
  enforceaccess: 'false'
  prefixchat: 'true'
  prefixchatformat: '[%world%]%chat%'
  useasyncchat: 'true'
  teleportintercept: 'true'
  firstspawnoverride: 'true'
  displaypermerrors: 'true'
  globaldebug: '0'
  silentstart: 'false'
  messagecooldown: '5000'
  version: '2.9'
  firstspawnworld: hub
  teleportcooldown: '1000'
  defaultportalsearch: 'false'
  portalsearchradius: '128'
  autopurge: 'true'
  idonotwanttodonate: 'false'
```
Doesn't really have anything related to world loading. You want the `worlds.yml` instead?
